/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MartaYLasPlantas;

import java.awt.GridLayout;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * @author EDGENP: Eugenio Lorente Darius Tamas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secreto = new javax.swing.JTextField();
        dniTexto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cargarPartida = new javax.swing.JLabel();
        empezar = new javax.swing.JLabel();
        ranking = new javax.swing.JLabel();
        confirmarTruco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        secreto.setBackground(new java.awt.Color(124, 105, 89));
        secreto.setForeground(new java.awt.Color(255, 255, 255));
        secreto.setText("Secretos?");
        secreto.setBorder(null);
        secreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secretoActionPerformed(evt);
            }
        });
        getContentPane().add(secreto);
        secreto.setBounds(290, 290, 80, 16);

        dniTexto.setBackground(new java.awt.Color(124, 105, 89));
        dniTexto.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        dniTexto.setForeground(new java.awt.Color(255, 255, 255));
        dniTexto.setText("DNI:");
        dniTexto.setBorder(null);
        dniTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTextoActionPerformed(evt);
            }
        });
        getContentPane().add(dniTexto);
        dniTexto.setBounds(300, 230, 103, 16);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(66, 157, 412, 0);

        cargarPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Menu/botonCargar.png"))); // NOI18N
        cargarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarPartidaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cargarPartidaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cargarPartidaMouseReleased(evt);
            }
        });
        getContentPane().add(cargarPartida);
        cargarPartida.setBounds(430, 300, 80, 60);

        empezar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Menu/botonComenzar.png"))); // NOI18N
        empezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empezarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                empezarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                empezarMouseReleased(evt);
            }
        });
        getContentPane().add(empezar);
        empezar.setBounds(430, 240, 100, 60);

        ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Menu/botonRankings.png"))); // NOI18N
        ranking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankingMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rankingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rankingMouseReleased(evt);
            }
        });
        getContentPane().add(ranking);
        ranking.setBounds(40, 330, 60, 40);

        confirmarTruco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Menu/botonTrucos.png"))); // NOI18N
        confirmarTruco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarTrucoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmarTrucoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confirmarTrucoMouseReleased(evt);
            }
        });
        getContentPane().add(confirmarTruco);
        confirmarTruco.setBounds(380, 280, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Menu/TumbaDesarrolladores.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 220, 70, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Menu/menuAjustado.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, -4, 560, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dniTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTextoActionPerformed

    private void secretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secretoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_secretoActionPerformed

    private void empezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empezarMouseClicked
        if (!dniTexto.getText().equals("DNI:")) {
            try {
                PrincipalGraficos.setJugador(Jugador.registrarse(dniTexto.getText()));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            Ejecutar.tableroVisible();
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Introduce un DNI para empezar.");
        }
    }//GEN-LAST:event_empezarMouseClicked

    private void cargarPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarPartidaMouseClicked

        Jugador.leerJugadores();
        String dni = dniTexto.getText();
        HashMap<String, Jugador> jugadores = Jugador.getJugadores();
        try {
            if (dni != null) {
                if (Jugador.existeJugador(dni)) {
                    Jugador jugador = jugadores.get(dni);
                    PrincipalGraficos.cargarPartida(jugador);
                    PrincipalGraficos.setPartidaCagada(true);
                    PrincipalGraficos.setJugador(jugador);
                    Ejecutar.tableroVisible();
                    this.setVisible(false);
                }
            }
        } catch (FileNotFoundException fnfe) {
            JOptionPane.showMessageDialog(null, "No se ha encontrado el archivo. ");
        }

        // TODO add your handling code here:

    }//GEN-LAST:event_cargarPartidaMouseClicked

    private void rankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankingMouseClicked
        Jugador.leerJugadores();
        String dni = dniTexto.getText();
        int dificultad;
        HashMap<String, Jugador> jugadores = Jugador.getJugadores();
        HashMap<String, Integer> hashDificultad = new HashMap<>();

        hashDificultad.put("BAJA", 1);
        hashDificultad.put("MEDIA", 2);
        hashDificultad.put("ALTA", 3);
        hashDificultad.put("IMPOSIBLE", 4);

        Object[] opcionesDificultad = {"Elegir", "Salir"};
        JPanel panelDificultad = new JPanel();
        JComboBox boxDificultad = new JComboBox();
        boxDificultad.addItem("BAJA");
        boxDificultad.addItem("MEDIA");
        boxDificultad.addItem("ALTA");
        boxDificultad.addItem("IMPOSIBLE");

        panelDificultad.add(boxDificultad);

        int opcionDificultad = JOptionPane.showOptionDialog(null, panelDificultad, "Elegir dificultad",
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, opcionesDificultad, null);
        String strDificultad = (String) boxDificultad.getSelectedItem();

        if (opcionDificultad == JOptionPane.YES_OPTION) {
            JPanel panel = new JPanel();
            Object[] opciones = {"Salir"};
            dificultad = hashDificultad.get(strDificultad);
            Jugador lista[] = Jugador.ranking(dificultad);
            panel.setLayout(new GridLayout(lista.length, 1));

            int i = 1;
            for (Jugador jug : lista) {
                panel.add(new JLabel(i + ": " + jug.getNombre() + ": "
                        + jug.getPuntuacion()[dificultad - 1] + "puntos"));
                i++;
            }

            JOptionPane.showOptionDialog(null, panel, "RANKINGS",
                    JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE,
                    null, opciones, null);
        }
    }//GEN-LAST:event_rankingMouseClicked

    private void confirmarTrucoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarTrucoMouseClicked

        ArrayList<String> trucos = new ArrayList<>();
        trucos.add("minecraft");
        trucos.add("magia");
        trucos.add("casimiro");
        trucos.add("veganos");

        if (trucos.contains(secreto.getText())) {
            JOptionPane.showMessageDialog(null, "codigo aceptado");
        } else {
            JOptionPane.showMessageDialog(null, "Codigo rechazado");
        }

        switch (secreto.getText()) {
            case "minecraft":
                PrincipalGraficos.setMinecraft(true);
                break;
            case "magia":
                PrincipalGraficos.setMagos(true);
                break;
            case "casimiro":
                PrincipalGraficos.setSecret(true);
                break;
            case "veganos":
                PrincipalGraficos.setVeganos(true);
                break;
        }
        secreto.setText("");
    }//GEN-LAST:event_confirmarTrucoMouseClicked

    private void empezarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empezarMousePressed
        ImageIcon empezarBotonP = new ImageIcon(getClass().getResource("/res/Menu/botonComenzarPulsado.png"));
        empezar.setIcon(empezarBotonP);
    }//GEN-LAST:event_empezarMousePressed

    private void empezarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empezarMouseReleased
        ImageIcon empezarBoton = new ImageIcon(getClass().getResource("/res/Menu/botonComenzar.png"));
        empezar.setIcon(empezarBoton);
    }//GEN-LAST:event_empezarMouseReleased

    private void cargarPartidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarPartidaMousePressed
        ImageIcon cargarPartidaBotonP = new ImageIcon(getClass().getResource("/res/Menu/botonCargarPulsado.png"));
        cargarPartida.setIcon(cargarPartidaBotonP);
    }//GEN-LAST:event_cargarPartidaMousePressed

    private void cargarPartidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarPartidaMouseReleased
        ImageIcon cargarPartidaB = new ImageIcon(getClass().getResource("/res/Menu/botonCargar.png"));
        cargarPartida.setIcon(cargarPartidaB);
    }//GEN-LAST:event_cargarPartidaMouseReleased

    private void confirmarTrucoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarTrucoMousePressed
        ImageIcon TrucoBotons = new ImageIcon(getClass().getResource("/res/Menu/botonTrucosPulsado.png"));
        confirmarTruco.setIcon(TrucoBotons);
    }//GEN-LAST:event_confirmarTrucoMousePressed

    private void confirmarTrucoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarTrucoMouseReleased
        ImageIcon TrucoBotonLibre = new ImageIcon(getClass().getResource("/res/Menu/botonTrucos.png"));
        confirmarTruco.setIcon(TrucoBotonLibre);
    }//GEN-LAST:event_confirmarTrucoMouseReleased

    private void rankingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankingMousePressed
        ImageIcon rankingBotonP = new ImageIcon(getClass().getResource("/res/Menu/botonRankingsPulsado.png"));
        ranking.setIcon(rankingBotonP);
    }//GEN-LAST:event_rankingMousePressed

    private void rankingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankingMouseReleased
        ImageIcon rankingBoton = new ImageIcon(getClass().getResource("/res/Menu/botonRankings.png"));
        ranking.setIcon(rankingBoton);
    }//GEN-LAST:event_rankingMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cargarPartida;
    private javax.swing.JLabel confirmarTruco;
    private javax.swing.JTextField dniTexto;
    private javax.swing.JLabel empezar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ranking;
    private javax.swing.JTextField secreto;
    // End of variables declaration//GEN-END:variables
}
